package net.tecgurus.sistemabancario.entities;
// Generated 23-dic-2017 11:01:38 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "cuenta", catalog = "sistemabancario")
public class Cuenta implements java.io.Serializable {

	private Integer idCuenta;
	private Cliente cliente;
	private Tipocuenta tipocuenta;
	private int numeroCuenta;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public Cuenta() {
	}

	public Cuenta(Cliente cliente, Tipocuenta tipocuenta, int numeroCuenta) {
		this.cliente = cliente;
		this.tipocuenta = tipocuenta;
		this.numeroCuenta = numeroCuenta;
	}

	public Cuenta(Cliente cliente, Tipocuenta tipocuenta, int numeroCuenta, Set<Movimiento> movimientos) {
		this.cliente = cliente;
		this.tipocuenta = tipocuenta;
		this.numeroCuenta = numeroCuenta;
		this.movimientos = movimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idCuenta", unique = true, nullable = false)
	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoCuenta", nullable = false)
	public Tipocuenta getTipocuenta() {
		return this.tipocuenta;
	}

	public void setTipocuenta(Tipocuenta tipocuenta) {
		this.tipocuenta = tipocuenta;
	}

	@Column(name = "numeroCuenta", nullable = false)
	public int getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(int numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuenta")
	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
