package net.tecgurus.sistemabancario.entities;
// Generated 23-dic-2017 11:01:38 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "sistemabancario")
public class Perfil implements java.io.Serializable {

	private Integer idPerfil;
	private String nombre;
//	private Set<Login> logins = new HashSet<Login>(0);

	public Perfil() {
	}

	public Perfil(String nombre) {
		this.nombre = nombre;
	}

//	public Perfil(String nombre, Set<Login> logins) {
//		this.nombre = nombre;
//		this.logins = logins;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPerfil", unique = true, nullable = false)
	public Integer getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(Integer idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
//	public Set<Login> getLogins() {
//		return this.logins;
//	}
//
//	public void setLogins(Set<Login> logins) {
//		this.logins = logins;
//	}

}
