package net.tecgurus.sistemabancario.entities;
// Generated 23-dic-2017 11:01:38 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocuenta generated by hbm2java
 */
@Entity
@Table(name = "tipocuenta", catalog = "sistemabancario")
public class Tipocuenta implements java.io.Serializable {

	private Integer idTipoCuenta;
	private String nombre;
	private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

	public Tipocuenta() {
	}

	public Tipocuenta(String nombre) {
		this.nombre = nombre;
	}

	public Tipocuenta(String nombre, Set<Cuenta> cuentas) {
		this.nombre = nombre;
		this.cuentas = cuentas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoCuenta", unique = true, nullable = false)
	public Integer getIdTipoCuenta() {
		return this.idTipoCuenta;
	}

	public void setIdTipoCuenta(Integer idTipoCuenta) {
		this.idTipoCuenta = idTipoCuenta;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocuenta")
	public Set<Cuenta> getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set<Cuenta> cuentas) {
		this.cuentas = cuentas;
	}

}
