package net.tecgurus.sistemabancario.entities;
// Generated 23-dic-2017 11:01:38 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipomovimiento generated by hbm2java
 */
@Entity
@Table(name = "tipomovimiento", catalog = "sistemabancario")
public class Tipomovimiento implements java.io.Serializable {

	private Integer idTipoMovimiento;
	private String nombre;
	private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

	public Tipomovimiento() {
	}

	public Tipomovimiento(String nombre) {
		this.nombre = nombre;
	}

	public Tipomovimiento(String nombre, Set<Movimiento> movimientos) {
		this.nombre = nombre;
		this.movimientos = movimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoMovimiento", unique = true, nullable = false)
	public Integer getIdTipoMovimiento() {
		return this.idTipoMovimiento;
	}

	public void setIdTipoMovimiento(Integer idTipoMovimiento) {
		this.idTipoMovimiento = idTipoMovimiento;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipomovimiento")
	public Set<Movimiento> getMovimientos() {
		return this.movimientos;
	}

	public void setMovimientos(Set<Movimiento> movimientos) {
		this.movimientos = movimientos;
	}

}
