package net.tecgurus.sistemabancario.entities;
// Generated 23-dic-2017 11:01:38 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuariorol generated by hbm2java
 */
@Entity
@Table(name = "usuariorol", catalog = "sistemabancario")
public class Usuariorol implements java.io.Serializable {

	private Integer idusuariorol;
	private Rol rol;
	private Usuario usuario;

	public Usuariorol() {
	}

	public Usuariorol(Rol rol, Usuario usuario) {
		this.rol = rol;
		this.usuario = usuario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idusuariorol", unique = true, nullable = false)
	public Integer getIdusuariorol() {
		return this.idusuariorol;
	}

	public void setIdusuariorol(Integer idusuariorol) {
		this.idusuariorol = idusuariorol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idrole", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
